application: nusmodulereview
version: 1
runtime: python27
api_version: 1
threadsafe: true


# handlers:
#- url: /.*
#  script: helloworld.py
# Every request to a URL whose path matches the regular expression /.* (all URLs) should be handled by the helloworld.py script.

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /json
  static_dir: json

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page(front.py)
- url: /
  script: front.app

# Handler for login and redirection
- url: /_ah/login_required
  script: login.app

# All other pages require login (main.py)
- url: /.*
  script: main.app
  login: required


libraries:
- name: jinja2
  version: latest


 # $.getJSON('people.json', function(data) {


#When you specify "people.json", you're referring to the file "people.json" in the same directory as the script. This is a relative path. What you want is 

#"/json/people.json".
#FYI: other usual notations are: "./people.json" - explicitly state that we should look in the same folder. "../people.json" - look one folder above. "json/people.json" - note the missing leading slash. This refers to the folder json in the current folder, and then the file people.json
