application: nusmodulereview
version: 1
runtime: python27
api_version: 1
threadsafe: true


# handlers:
#- url: /.*
#  script: helloworld.py
# Every request to a URL whose path matches the regular expression /.* (all URLs) should be handled by the helloworld.py script.

handlers:

- url: /stylesheets
static_dir: stylesheets

- url: /images
static_dir: images

- url: /scripts
static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
static_dir: bootstrap

# Handler for front page(front.py)
- url: /
script: front.app

# Handler for login and redirection
- url: /_ah/login_required
script: login.app

# All other pages require login (giftbook.py)
- url: /.*
script: giftbook.app
login: required

libraries:
- name: jinja2
version: latest